"""
Promiedos module.
"""

from . import types
from .client import PromiedosClient
from .types import (
    Color,
    Event,
    EventItem,
    EventType,
    GlobalScores,
    League,
    Lineups,
    LineupTeam,
    MainOdds,
    Match,
    MatchEvents,
    MatchStats,
    MatchStatus,
    OddsOption,
    Penalties,
    Player,
    Players,
    Scores,
    Stage,
    Status,
    Substitution,
    Team,
    Tournament,
    TVNetwork,
)

__all__ = [
    "PromiedosClient",
    "types",
    "Color",
    "Event",
    "EventItem",
    "EventType",
    "GlobalScores",
    "League",
    "Lineups",
    "LineupTeam",
    "MainOdds",
    "Match",
    "MatchEvents",
    "MatchStats",
    "MatchStatus",
    "OddsOption",
    "Penalties",
    "Player",
    "Players",
    "Scores",
    "Stage",
    "Status",
    "Substitution",
    "TVNetwork",
    "Team",
    "Tournament",
]
