"""
Sofascore client module.
"""

from . import types
from .client import SofascoreClient
from .types import (
    Bracket,
    Category,
    Comment,
    CommentType,
    EntityType,
    Event,
    Incident,
    IncidentType,
    Lineups,
    MatchStats,
    Player,
    PlayerAttributes,
    PlayerLineup,
    Season,
    Shot,
    Standing,
    Status,
    StatusType,
    Team,
    TeamColor,
    TeamLineup,
    TopPlayersMatch,
    TopTournamentPlayers,
    TopTournamentTeams,
    Tournament,
    TransferHistory,
)

__all__ = [
    "SofascoreClient",
    "types",
    "EntityType",
    "Category",
    "Event",
    "Player",
    "Team",
    "Tournament",
    "Season",
    "MatchStats",
    "Lineups",
    "Status",
    "StatusType",
    "Incident",
    "IncidentType",
    "Shot",
    "Comment",
    "CommentType",
    "Standing",
    "Bracket",
    "TopPlayersMatch",
    "TopTournamentPlayers",
    "TopTournamentTeams",
    "PlayerAttributes",
    "PlayerLineup",
    "TeamColor",
    "TeamLineup",
    "TransferHistory",
]
